## Vector

In [1]:
import numpy as np

In [34]:
m = np.array([[3,4],[1,2]])
m.shape

v = np.array([1,2,3])
v.reshape(1,3)

array([[1],
       [2],
       [3]])

In [37]:
v.reshape(3,1)

array([[1],
       [2],
       [3]])

In [45]:
x = np.array(7)
x.shape

()

In [53]:
m = np.array([[1,2,3],[3,2,1]])
n = np.array([[5,4,3],[2,2,2]])

o = np.array([m,n])
o

array([[[1, 2, 3],
        [3, 2, 1]],

       [[5, 4, 3],
        [2, 2, 2]]])

In [55]:
m+n

array([[6, 6, 6],
       [5, 4, 3]])

In [57]:
m-n

array([[-4, -2,  0],
       [ 1,  0, -1]])

In [66]:
x = np.array([[1,2,3],[2,12,4]])
y = np.array([[9,8,1],[0,6,9]])
x+y

array([[10, 10,  4],
       [ 2, 18, 13]])

### Addition with scalar

In [67]:
x + 5 - 1

array([[ 5,  6,  7],
       [ 6, 16,  8]])

In [68]:
y + np.array(7)

array([[16, 15,  8],
       [ 7, 13, 16]])

### Transpose

In [72]:
x.T

array([[ 1,  2],
       [ 2, 12],
       [ 3,  4]])

In [75]:
s = np.array(5)
s.T

array(5)

In [82]:
v = np.array([6,2,4])
v.reshape(1,3).T

array([[6],
       [2],
       [4]])

In [84]:
v

array([6, 2, 4])

### Multiplication

In [88]:
v1 = np.array([[1,2,3],[1,2,0]])
v2 = np.array([[2,3],[0,1],[0,1]])

np.dot(v1,v2)

array([[2, 8],
       [2, 5]])